### ISSUE TITLE
Difference between this and drf-typed-views

### ISSUE THREAD

**Issue by uptickmetachu** [rsinger86/drf-typed#1]
Hi just came across this repo while looking for adding typed functionality to drf (like fastapi) and it looks perfect!

Is this meant to be the successor/reimplementation to your other project drf-typed-views?

And I know this repo is listed as beta, is it currently being used in production anywhere or still pending release.

**Comment by rsinger86** [comment]
Hi - thank you for your interest. 

This project is meant to be a successor/replacement for drf-typed-views. 

I've been meaning to tidy up a few more things, do an official release, and update the other project's readme to direct users to this project. Just been swamped with other stuff lately.
